<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>RulesEngine.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\RulesEngine.Analysis\RulesEngine.Analysis.csproj" />
        <ProjectReference Include="..\RulesEngine.RuleModel\RulesEngine.RuleModel.csproj" />
    </ItemGroup>

</Project>
