using System.Text.Json.Nodes;
using CodeGuard.Configuration.Capabilities;
using CsCheck;

namespace CodeGuard.RuleFuzzing.Tests.Generation;

/// <summary>
/// One <c>Gen&lt;JsonNode?&gt;</c> per <see cref="ParameterType"/> (excluding <see cref="ParameterType.Selector"/>
/// and <see cref="ParameterType.AssertionList"/>, which are recursive and built by
/// <see cref="SelectorGenerator"/>/<see cref="AssertionGenerator"/> instead, since they need the
/// catalog and a depth budget rather than just a value). Every leaf mixes a benign pool with
/// <see cref="AdversarialCorpus"/> via <see cref="RuleFuzzOptions.AdversarialValueWeight"/>.
/// </summary>
internal static class ParameterValueGenerator
{
    private static readonly string[] BenignFragments =
    [
        "Contoso", "Domain", "Entities", "Handlers", "Services", "Repository", "Order", "Customer",
        "Invoice", "Payment", "Value", "Aggregate", "Command", "Query"
    ];

    private static readonly Gen<string> BenignWord = Gen.OneOfConst(BenignFragments);

    private static readonly Gen<string> BenignDottedPath =
        BenignWord.Select(BenignWord, (a, b) => $"{a}.{b}").Select(BenignWord, (ab, c) => $"{ab}.{c}*");

    private static readonly Gen<string> BenignSlashPath =
        BenignWord.Select(BenignWord, (a, b) => $"{a}/{b}/*.cs");

    private static Gen<JsonNode?> Wrap(Gen<string> gen) => gen.Select(v => (JsonNode?)JsonValue.Create(v));

    public static Gen<JsonNode?> ForParameter(ParameterDescriptor parameter) => parameter.Type switch
    {
        ParameterType.String => StringValue(),
        ParameterType.Glob => GlobValue(),
        ParameterType.Regex => RegexValue(),
        ParameterType.Bool => Gen.Bool.Select(b => (JsonNode?)JsonValue.Create(b)),
        ParameterType.Int => IntValue(),
        ParameterType.StringList => StringListValue(),
        ParameterType.Enum => EnumValue(parameter),
        _ => throw new NotSupportedException(
            $"{parameter.Type} is recursive and must be generated by SelectorGenerator/AssertionGenerator, not ParameterValueGenerator.")
    };

    private static Gen<JsonNode?> StringValue() => Wrap(Gen.Frequency(
        (RuleFuzzOptions.BenignValueWeight, BenignWord),
        (RuleFuzzOptions.AdversarialValueWeight, Gen.OneOfConst(AdversarialCorpus.Strings))));

    private static Gen<JsonNode?> GlobValue() => Wrap(Gen.Frequency(
        (RuleFuzzOptions.BenignValueWeight, Gen.OneOf(BenignDottedPath, BenignSlashPath, BenignWord)),
        (RuleFuzzOptions.AdversarialValueWeight, Gen.OneOfConst(AdversarialCorpus.Globs))));

    private static Gen<JsonNode?> RegexValue() => Wrap(Gen.Frequency(
        (RuleFuzzOptions.BenignValueWeight, BenignWord.Select(w => $"^{w}.*$")),
        (RuleFuzzOptions.AdversarialValueWeight, Gen.OneOfConst(AdversarialCorpus.Regexes))));

    private static Gen<JsonNode?> IntValue() => Gen.Frequency(
        (RuleFuzzOptions.BenignValueWeight, Gen.Int[0, 10]),
        (RuleFuzzOptions.AdversarialValueWeight, Gen.OneOfConst(AdversarialCorpus.Ints)))
        .Select(i => (JsonNode?)JsonValue.Create(i));

    private static Gen<JsonNode?> StringListValue()
    {
        var benignList = StringValue().Array[1, 4]
            .Select(values => (JsonNode?)new JsonArray(values));
        var adversarialList = Gen.OneOf(
            // Deliberately empty - probes the "required but not non-empty" gap. A fresh JsonArray per
            // generation, not Gen.Const(new JsonArray()): System.Text.Json.Nodes tracks a single parent
            // per node, so reusing one pre-built instance across iterations throws "already has a
            // parent" the second time it's attached - see JsonObjectGenExtensions.NewObject's doc comment.
            Gen.Bool.Select(_ => (JsonNode?)new JsonArray()),
            StringValue().Array[200, 250].Select(values => (JsonNode?)new JsonArray(values)));

        return Gen.Frequency(
            (RuleFuzzOptions.BenignValueWeight, benignList),
            (RuleFuzzOptions.AdversarialValueWeight, adversarialList));
    }

    private static Gen<JsonNode?> EnumValue(ParameterDescriptor parameter)
    {
        var allowed = parameter.AllowedValues
            ?? throw new InvalidOperationException($"Enum parameter '{parameter.Name}' has no AllowedValues.");
        var validValue = Gen.OneOfConst(allowed.ToArray());
        var nearMissValue = Gen.OneOfConst(allowed.ToArray()).Select(v => v + "_x");

        return Wrap(Gen.Frequency(
            (RuleFuzzOptions.BenignValueWeight, validValue),
            (RuleFuzzOptions.AdversarialValueWeight, nearMissValue)));
    }
}
