<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>RulesEngine.Reporting</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\RulesEngine.Core\RulesEngine.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Sarif.Sdk" Version="5.5.0" />
    </ItemGroup>

</Project>
